version: "3.9"

services:
  # =========================
  # PHP LARAVEL (APP)
  # =========================
  php_laravel_1:
    build: ./php
    container_name: php_laravel_1
    hostname: php1
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - postgres_master
    networks:
      - laravel_load_balancing

  php_laravel_2:
    build: ./php
    container_name: php_laravel_2
    hostname: php2
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - postgres_master
    networks:
      - laravel_load_balancing

  # =========================
  # POSTGRES MASTER
  # =========================
  postgres_master:
    image: postgres:15
    container_name: postgres-master
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    volumes:
      - ./database/master:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    networks:
      - laravel_load_balancing

  # =========================
  # POSTGRES SLAVE
  # =========================
  postgres_slave:
    image: postgres:15
    container_name: postgres-slave
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    volumes:
      - ./database/slave:/var/lib/postgresql/data
    depends_on:
      - postgres_master
    networks:
      - laravel_load_balancing

  # =========================
  # NGINX (APP)
  # =========================
  nginx_laravel_1:
    image: nginx:latest
    container_name: nginx_laravel_1
    hostname: nginx1
    volumes:
      - ./src:/var/www/html
      - ./nginx/default1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_laravel_1
    networks:
      - laravel_load_balancing

  nginx_laravel_2:
    image: nginx:latest
    container_name: nginx_laravel_2
    hostname: nginx2
    volumes:
      - ./src:/var/www/html
      - ./nginx/default2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_laravel_2
    networks:
      - laravel_load_balancing

  # =========================
  # NGINX LOAD BALANCER
  # =========================
  nginx_loadbalancer:
    image: nginx:latest
    container_name: nginx_loadbalancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/loadbalancer.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nginx_laravel_1
      - nginx_laravel_2
    networks:
      - laravel_load_balancing

networks:
  laravel_load_balancing:
    driver: bridge
